# -*- coding: utf-8 -*-
"""Listas 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJbwrRiEL1yR66B8A80qgF7e9xrnUIW8

# Juntar Listas, Ordenar e Cuidados Especiais

### 2 formas:

- lista1.extend(lista2)
- lista_nova = lista1 + lista2

Obs: o Método .append não junta listas, mas adiciona um valor no final da lista
"""

produtos = ['apple tv', 'mac', 'iphone x', 'iphone 11', 'IPad', 'apple watch', 'mac book', 'airpods']
novos_produtos = ['iphone 12', 'ioculos']

todos_produtos = produtos + novos_produtos
print(todos_produtos)
print(novos_produtos)

produtos.extend(novos_produtos)
print(produtos)
print(novos_produtos)

# Inserir uma lista dentro de outra
produtos.append(novos_produtos)
print(produtos)

"""### Cuidado:

- [1] + [2] não é a mesma coisa que 1 + 2, então cuidado sempre com o formato dos valores na hora de fazer operações.
"""

vendas = [1000, 1500, 15000, 20000, 270, 900, 100, 1200]
vendas_iphonex = [15000]
vendas_iphone11 = [20000]

print([1] + [2])
print(1 + 2)

total_iphone = vendas[2] + vendas[3]
# Nesse formato seria juntado as listas somente
# total_iphone_listas = vendas_iphonex + vendas_iphone11
total_iphone_listas = vendas_iphonex [0] + vendas_iphone11 [0]
print(total_iphone)
print(total_iphone_listas)

"""### Ordenar listas

lista.sort()
"""
produtos.sort()
print(produtos)

vendas.sort()
print(vendas)