# -*- coding: utf-8 -*-
"""Listas 05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYyQHisbLGJDJgpQdc9_tRBiyoS3rQea

# Algumas Funções Básicas de Lista

## Tamanho da Lista

tamanho = len(lista)
"""

produtos = ['apple tv', 'mac', 'iphone x', 'IPad', 'apple watch', 'mac book', 'airpods']

"""- Quantos produtos temos a venda?"""

tamanho_da_lista = len(produtos)
print(tamanho_da_lista)

"""## Maior e Menor Valor

maior = max(lista)

menor = min(lista)
"""

vendas = [1000, 1500, 15000, 270, 900, 100, 1200]
mais_vendido = max(vendas)
menos_vendido = min(vendas)

print('O mais vendido teve {} vendas e o menos vendido teve {} vendas'.format(mais_vendido, menos_vendido))



# Qual o item mais vendido?
i = vendas.index(mais_vendido)
produto_mais_vendido = produtos[i]
print('O produto mais vendido foi {}'.format(produto_mais_vendido))


# Qual o item menos vendido?
i = vendas.index(menos_vendido)
produto_menos_vendido = produtos[i]
print('O produto menos vendido foi {}'.format(produto_menos_vendido))



