# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas_ano = vendas_1sem + vendas_2sem
melhor_mes = max(vendas_ano)
pior_mes = min(vendas_ano)

i_maior_valor = vendas_ano.index(melhor_mes)
i_menor_valor = vendas_ano.index(pior_mes)

print(vendas_ano)


"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""
print('O melhor mes do ano foi {} com {} vendas'.format(meses[i_maior_valor], melhor_mes))
print('O pior mes do ano foi {} com {} vendas'.format(meses[i_menor_valor], pior_mes))
fat_total = sum(vendas_ano)
print('O faturamento total do ano foi de R${:,}'.format(fat_total))
percentual = melhor_mes / fat_total
print('O melhor mes do ano representa {:.1%} do faturamento total anual'.format(percentual))

"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""
#print('O top 3 meses com mais vendas são'top3)
top3 = []

print(vendas_ano)
melhor_mes = max(vendas_ano)
vendas_ano.remove(melhor_mes)
print(melhor_mes)
top3.append(melhor_mes)
print(top3)
melhor_mes = max(vendas_ano)
vendas_ano.remove(melhor_mes)
print(vendas_ano)
top3.append(melhor_mes)
melhor_mes = max(vendas_ano)
vendas_ano.remove(melhor_mes)
print(top3)
melhor_mes = max(vendas_ano)
vendas_ano.remove(melhor_mes)
top3.append(melhor_mes)
print('As tres melhores valores de venda foram {}'.format(top3))


