# -*- coding: utf-8 -*-
"""Exercícios Módulo 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fPXuUS-NeoH8ABii8q2EKRU5LPdlGuA

# Exercícios do Módulo 1 - Operações, Variáveis e Input

### Parte 1 - Operações e Variáveis
Crie um programa que imprima (print) os principais indicadores da loja Hashtag&Drink no último ano.
Obs: faça tudo usando variáveis.

Valores do último ano:

Quantidade de Vendas de Coca = 150<br>
Quantidade de Vendas de Pepsi = 130<br>
Preço Unitário da Coca = 1,50 <br>
Preço Unitário da Pepsi = 1,50<br>
Custo da Loja: 2.500,00

Use o bloco abaixo para criar todas as variáveis que precisar.
"""
qtde_coca = 150
qtde_pepsi = 130
preco_coca = 1.50
preco_pepsi = 1.50
custo_loja = 2.500
faturamento = (qtde_coca * preco_coca) + (qtde_pepsi * preco_pepsi)
lucro = faturamento - custo_loja



"""1. Qual foi o faturamento de Pepsi da Loja?"""

print(f'A quantidade de vendas foi {qtde_pepsi * preco_pepsi}')

"""2. Qual foi o faturamento de Coca da Loja?"""

print(f'O faturamento de coca da loja é {qtde_coca * preco_coca}')

"""3. Qual foi o Lucro da loja?"""

print(f'O lucro total da loja foi {lucro}')


"""4. Qual foi a Margem da Loja? (Lembre-se, margem = Lucro / Faturamento). Não precisa formatar em percentual"""

print(f'A margem de lucro da loja foi {lucro / faturamento}')


